server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3307/adminapp-db2?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password:
    driverClassName: com.mysql.cj.jdbc.Driver
  application:
    name: spring-admin
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: login
            authorization-grant-type: authorization_code
            scope: openid
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/admin-app
            user-name-attribute: preferred_username
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/admin-app

  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true

info:
  application:
    name: admin-app
    version: '@project.version@'